apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-push-listener
spec:
  serviceAccountName: <service-account-name>
  triggers:
    - name: github-push-trigger
      bindings:
        - ref: github-push-binding
      template:
        ref: my-pipeline-template
