apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener
spec:
  serviceAccountName: default
  triggers:
    - name: github-trigger
      bindings:
        - ref: refs/heads/main
      template:
        ref: example-pipeline
