apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: my-pipeline-template
spec:
  params:
    - name: git-repo-url
      description: Git repository URL
    - name: git-repo-ref
      description: Git repository ref
    # Add other parameters as needed
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: my-pipeline-run-
      spec:
        pipelineRef:
          name: my-pipeline
        params:
          - name: git-repo-url
            value: $(params.git-repo-url)
          - name: git-repo-ref
            value: $(params.git-repo-ref)
          # Add other parameters as needed
