apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-push-binding
spec:
  params:
    - name: git-repo-url
      value: $(body.repository.url)
    - name: git-repo-ref
      value: $(body.ref)
    # Add other parameters as needed
