apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kubectl-apply-task
spec:
  steps:
    - name: apply-pod
      image: bitnami/kubectl
      command:
        - kubectl
      args:
        - apply
        - -f
        - $(resources.inputs.artifacts.location)/pod.yaml
