apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - name: github-trigger
      interceptors:
        - cel:
            filter: "body"
      bindings:
        - name: github-binding
      template:
        ref: github-template
