apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-nginx-pod
spec:
  resources:
    - name: source-repo
      type: git
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      resources:
        inputs:
          - name: source
            resource: source-repo
      params:
        - name: url
          value: $(resources.inputs.source.url)
        - name: revision
          value: $(resources.inputs.source.revision)
    - name: deploy-pod
      taskRef:
        name: deploy-pod
