# Tekton Pipeline for applying pod.yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: apply-pod-pipeline
spec:
  tasks:
    - name: apply-pod-task
      taskRef:
        name: kubectl-apply-task
      resources:
        inputs:
          - name: workspace
            type: git
