apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-trigger
spec:
  params:
    - name: gitrevision
      description: The git revision to checkout
      default: "master"
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: source-repo
      spec:
        type: git
        params:
          - name: revision
            value: $(tt.params.gitrevision)
          - name: url
            value: $(body.repository.clone_url)
